Default: &defaults
  database: azulit.sqlite3
  poolsize: 10

Development:
  <<: *defaults

Testing:
  database: azulit_test.sqlite3
  <<: *defaults

Staging:
  database: azulit_staging.sqlite3
  poolsize: 100
  <<: *defaults

Production:
  database: azulit_production.sqlite3
  poolsize: 100
  <<: *defaults
